export {
  Registration,
  Login,
  Profile,
  login,
  register,
  authReducer,
  getIsLoggedIn,
  getIsRegistration,
  setIsLoggedIn,
  setIsRegistration,
  logout,
  setName,
  setEmail,
  getEmail,
  getName,
} from './auth';
export {
  NewPassword,
  ForgotPassword,
  CheckEmail,
  forgotReducer,
  updateUserPassword,
  recoverUserPassword,
  updateUserName,
  updatePassword,
  updateUser,
  recoverPassword,
} from './forgot';
